# General Settings
logo: https://s3.eu-west-2.amazonaws.com/grubdaily/logoblue.png
name: Grubdaily
description: For tasty things
site_owner_name: Thomas Corley
email: thomcorley@gmail.com
favicon: /favicon.png
twitter_handler: your_handler
analytics_code: UA-XXXXXXX-2
disqus: your_disqus_site

# Social Accounts
social_networks:
-  { name: facebook, url: 'http://facebook.com' }
-  { name: twitter, url: 'http://twitter.com' }
-  { name: instagram, url: 'http://www.instagram.com' }
-  { name: google-plus, url: 'http://plus.google.com' }
-  { name: linkedin, url: '' }
-  { name: skype, url: '' }
-  { name: github, url: '' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: 'http://www.pinterest.co.uk' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }

# Modules Settings
show_tags: 1
show_email: 0
show_rss: 0
show_comments: 0

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "false"

# Serving
url: "https://thomcorley.github.io"
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/recipes/:num/"

# Conversion
markdown: kramdown

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed
