# General Settings
logo: https://s3.eu-west-2.amazonaws.com/grubdaily/grubdaily_white.png
name: grubdaily
description: For tasty things
site_owner_name: Thomas Corley
email: thomcorley@gmail.com
favicon: /favicon.png
twitter_handler: your_handler
disqus: your_disqus_site
google_analytics: UA-109063146-1

# Social Accounts
social_networks:
-  { name: facebook, url: 'http://facebook.com/grubdaily' }
-  { name: twitter, url: 'http://twitter.com/grubdaily_tom' }
-  { name: instagram, url: 'http://www.instagram.com/grubdaily' }
-  { name: google-plus, url: 'http://plus.google.com/115527733566953440139' }
-  { name: linkedin, url: '' }
-  { name: skype, url: '' }
-  { name: github, url: '' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: 'http://www.pinterest.co.uk/grubdaily' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }

# Modules Settings
show_tags: 1
show_email: 0
show_rss: 0
show_comments: 0

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "false"

# Serving
url: "https://www.grubdaily.com"
baseurl: ""

# Includes
include: ["_pages", "_redirects"]

# Outputting
permalink: /:title.html
category_dir: categories
tag_dir: tag

# Pagination
paginate: 10
paginate_path: "/recipes/:num/"

# Conversion
markdown: kramdown

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed

plugins_dir:
  - jekyll-sitemap
